name: Suggestion
description: Make a suggestion for OnlySoftwares

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING A SUGGESTION

        **You will be blocked from making suggestions if you don't follow all the rules stated here.**
        **Blatant duplicates will result in a ban.**

        Before making a suggestion, please make sure that a similiar one doesn't exist by [searching it](https://github.com/onlysoftwares/suggestions/issues?q=is%3Aissue).

        If a similar request already exists, **DO NOT reply** something like "i want this as well". Instead, react with :+1:. Only reply if you want to add additional info.

        Skip formalities like "hello" and do not use AI to "spice up" your suggestion. Keep it short and concise with only the information necessary.
        ## One Suggestion per issue

        Do not include multiple requests in one issue. If you are making 5 suggestions, make 5 separate issues

        # Do not suggest any of these:
        - Things that are not softwares
        - A suggestion about a product
        - An inappropiate suggestion
          - A NSFW Suggestion
          - A suggestion that includes bad words

  - type: textarea
    id: description
    attributes:
      label: Suggestion Description
      placeholder: Explain the suggestion in detail
    validations:
      required: true

  - type: checkboxes
    id: agreement-check
    attributes:
      label: Suggestion Agreement
      options:
        - label: I read the above and made sure my suggestion is possible and allowed
          required: false
        - label: I have read all the rules and followed them
          required: false
        - label: "I [searched the existing issues](https://github.com/onlysoftwares/suggestions/issues?q=is%3Aissue) and made sure a similar suggestion doesn't already exist"
          required: false
